//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POScreen.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLine
    {
        public long Id { get; set; }
        public string Shipment { get; set; }
        public string PONumber { get; set; }
        public string Line { get; set; }
    }
}
