//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POScreen.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public long Id { get; set; }
        public string ShipmentNumber { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public string ShipmentType { get; set; }
        public string ContainerNumber { get; set; }
        public string DeliveryLocation { get; set; }
        public string PO1 { get; set; }
        public string PO2 { get; set; }
        public string PO3 { get; set; }
        public string PO4 { get; set; }
        public string PO5 { get; set; }
        public string PO6 { get; set; }
        public string PO7 { get; set; }
        public string PO8 { get; set; }
        public string PO9 { get; set; }
        public string PO10 { get; set; }
        public string PO11 { get; set; }
        public string PO12 { get; set; }
        public string PO13 { get; set; }
        public string PO14 { get; set; }
        public string PO15 { get; set; }
        public string PO16 { get; set; }
        public string PO17 { get; set; }
        public string PO18 { get; set; }
        public string PO19 { get; set; }
        public string PO20 { get; set; }
    }
}
