//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POScreen.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SysproCompanyTEntities : DbContext
    {
        public SysproCompanyTEntities()
            : base("name=SysproCompanyTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApSupplier> ApSuppliers { get; set; }
        public virtual DbSet<PorMasterDetail> PorMasterDetails { get; set; }
        public virtual DbSet<PorSupStkInfo> PorSupStkInfoes { get; set; }
        public virtual DbSet<ChangeLog> ChangeLogs { get; set; }
        public virtual DbSet<ChangeLogExclusion> ChangeLogExclusions { get; set; }
        public virtual DbSet<vwPOList> vwPOLists { get; set; }
        public virtual DbSet<vwPOBrowseList> vwPOBrowseLists { get; set; }
        public virtual DbSet<PorMasterDetail_> PorMasterDetail_ { get; set; }
    }
}
