//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POScreen.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_FetchBOReport
    {
        public string SalesOrder { get; set; }
        public string Salesperson { get; set; }
        public string OrderDate { get; set; }
        public Nullable<System.DateTime> ODate { get; set; }
        public string ReqShipDate { get; set; }
        public string CustomerPoNumber { get; set; }
        public string Branch { get; set; }
        public string Warehouse { get; set; }
        public string CustomerName { get; set; }
        public string Customer { get; set; }
        public string MStockCode { get; set; }
        public string MStockDes { get; set; }
        public string MWarehouse { get; set; }
        public Nullable<decimal> MOrderQty { get; set; }
        public Nullable<decimal> MShipQty { get; set; }
        public Nullable<decimal> MBackOrderQty { get; set; }
        public string MOrderUom { get; set; }
        public Nullable<decimal> QtyOnHand { get; set; }
        public string OrderStatus { get; set; }
        public string FullfillBO { get; set; }
        public decimal MUnitCost { get; set; }
        public string ShippingInstruction { get; set; }
        public string ProductionStatus { get; set; }
        public string Courier { get; set; }
        public string ConNote { get; set; }
        public string PickedBy { get; set; }
    }
}
